name: Initialize

description: >
  Copies the PowerShell modules to a location defined in PSModulePath (since GHA doesn't allow manipulating
  environment variables) and also installs and imports them. If you are using this action and the "azure/login" action
  with "enable-AzPSSession: true" in the same workflow, make sure to run this action before "azure/login" otherwise
  login can fail.

runs:
  using: "composite"
  steps:
    - name: Display PowerShell Host Properties
      shell: pwsh
      run: |
        Write-Output "Current PowerShell host:"
        Get-Host

    - name: Copy Modules
      shell: pwsh
      run: |
        $sourcePath = (Resolve-Path "${{ github.action_path }}/../../..").Path
        $destinationPath = ($env:PSModulePath -split [IO.Path]::PathSeparator)[0]
        foreach ($modulePath in (Get-ChildItem $sourcePath -Recurse -Include "*.psm1"))
        {
          New-Item -ItemType Directory -Path $destinationPath -Name $modulePath.Directory.Name -Force
          Copy-Item $modulePath -Destination (Join-Path -Path $destinationPath -ChildPath $modulePath.Directory.Name)
        }

    - name: Install and Import Modules
      shell: pwsh
      run: |
        Install-Module Az -RequiredVersion 10.4.1 -AllowClobber -Force
        Install-Module SqlServer -RequiredVersion 22.1.1 -AllowClobber -Force

        foreach ($moduleName in (Get-ChildItem -Directory | select Name))
        {
          if (Test-Path -Path $moduleName/$moduleName.psm1)
          {
            Import-Module $moduleName.Name
          }
        }

        Get-Module -ListAvailable
