name: Initialize

on:
  workflow_dispatch:

defaults:
  run:
    shell: pwsh

jobs:
  build:
    runs-on: [ubuntu-latest, windows-latest]
    steps:
      - uses: actions/checkout@v3
      - name: Setup
        run: |
          "${{ github.action_path }}" >> $Env:GITHUB_PATH
      - name: Test
        run: |
          Get-Rekt
